### ISSUE TITLE
[Feat] 추가 UI 수정 및 구현

### ISSUE THREAD

**Issue by EnnzoKim** [Favor-Gift-Reminder/Favor-iOS#162]
## 📋 설명

- 아래 체크리스트 

> 일단 나머지 것들 생각나는대로 적어봤는데 자질구레한게 많아서 이 브랜치에 퉁 치고 구현하는 게 좋아 보이는 것 같아 ! 
피그마보면서 또 구현해야할 것들 있으면 체크리스트 계속 업데이트 할게 ~! 

## ✅ 체크리스트

> 구현해야하는 이슈 체크리스트
- [x] 유저인 친구 프로필 이미지에 `userIndicator` 표시하기
  - `FavorProfileImageVIew`의 `.small` 타입으로 구현해뒀어! 넣어주기만 하면 될 듯
- [x] 친구목록 하이라이트 되는 UI 수정
- [x] ToastManager 변경된 UI로 변경 및 필요한 곳에 띄우기 
- [x] 화면을 연결, (TabBar숨기기 및 NavigationBar 뒤로가기 버튼 설정)
- [x] `BaseProfileVC`를 상속받는 VC의 CollectionView 스크롤 시 제약조건 재설정
- [x] `MyPageVC`에 `FavorLabelButton`를 `NavigationBar`에 추가

**Comment by EnnzoKim** [comment]
>팝업화면은 전체적으로 통합해서 적용해주자

@nomatterjun 
형 혹시 이 말의 정확한 의미를 알 수 있을까?

**Comment by nomatterjun** [comment]
다른 팝업 화면들이랑 한번에 구현해주면 좋을 것 같아서 ㅎㅎ
