### ISSUE TITLE
[Bug] NavigationController Appearance 문제

### ISSUE THREAD

**Issue by nomatterjun** [Favor-Gift-Reminder/Favor-iOS#43]
## 📋 설명

<img src="https://user-images.githubusercontent.com/60438045/214291681-528a3dbd-61dc-4dcf-84c9-dd0dbca4be6b.png" width="450">

- 뒤로가기 버튼 에셋 누락
- 배경색이 `.clear`가 아닌 문제

## ✅ 체크리스트

> 구현해야하는 이슈 체크리스트
- [x] `ic_leftArrow` 에셋 추가
- [x] 배경색이 투명이 아닌 버그 해결

## 🔉 코멘트

방금 `dev` 브랜치를 머지해서 확인해봤는데
에셋에 `ic_leftArrow` 파일이 없더라고..!
뒤로가기 버튼은 그래서 기본 이미지로 표시되는 것 같고..

배경색은 왜 투명이 아닌지 모르겠어..!

<img width="1124" alt="스크린샷 2023-01-24 21 31 45" src="https://user-images.githubusercontent.com/60438045/214292363-39378d70-7ea1-4488-8974-7056eabf7994.png">

**Comment by EnnzoKim** [comment]
![image](https://user-images.githubusercontent.com/97531269/214294685-f3c268bb-faa5-45a1-a04f-d0b55abb9099.png)

```swift
  func setupNavigationBarAppearance() {
    let appearance = UINavigationBarAppearance()
    let backButtonAppearance = UIBarButtonItemAppearance()
    
    let leftArrowImage = UIImage(named: "ic_leftArrow")?
      .withRenderingMode(.alwaysOriginal)
      .withAlignmentRectInsets(UIEdgeInsets(top: 0, left: 0, bottom: 10, right: 0))
    
    backButtonAppearance.normal.titleTextAttributes = [
      .foregroundColor: UIColor.clear
    ]
    
    appearance.setBackIndicatorImage(leftArrowImage, transitionMaskImage: leftArrowImage)
    appearance.backButtonAppearance = backButtonAppearance
    
    appearance.titleTextAttributes = [
      .foregroundColor: UIColor.favorColor(.typo),
      .font: UIFont.favorFont(.bold, size: 18)
    ]
    
    // 이 부분 새로 추가 
    appearance.configureWithTransparentBackground() 
    appearance.backgroundColor = .clear
    appearance.shadowColor = nil
        
    UINavigationBar.appearance().compactAppearance = appearance
    UINavigationBar.appearance().standardAppearance = appearance
    UINavigationBar.appearance().scrollEdgeAppearance = appearance
  }
```

네비게이션 바 부분은
위 코드에서 주석 처리한 부분을 넣으면 될거야! 

그리고 나는 뒤로가기 이미지가 잘 나오는데 
어떻게 된 영문이지..?

![image](https://user-images.githubusercontent.com/97531269/214295181-8496341b-8645-48f6-a3b1-1b7ab03f14b7.png)

**Comment by nomatterjun** [comment]
오 일단 투명문제는 해결됐어! 👏👏👏

<img width="407" alt="스크린샷 2023-01-24 21 47 35" src="https://user-images.githubusercontent.com/60438045/214295527-111b6f0a-a6bf-4b1f-ab81-40d8b9619dcb.png">

머지 과정에서 지워진거 같아..
지금 `dev` 브랜치 pull 해서 파일 다시 올려서 커밋해줄 수 있을까..?

**Comment by EnnzoKim** [comment]
푸쉬했어 확인부탁!

**Comment by nomatterjun** [comment]
![스크린샷 2023-01-24 23 50 28](https://user-images.githubusercontent.com/60438045/214326550-89f63590-7591-4919-9957-1f1e30e98fdd.png)

음..
에셋들이 다 지워진채로 올라온거 같아...!
혹시 로컬 `.gitignore`에 포함되어 있나 확인해줄 수 있을까..?

**Comment by EnnzoKim** [comment]
어..! 해결된 것 같아
왜 `.gitignore`에 지정되어 있었지...??

`dev`에 푸쉬된 커밋 확인부탁해!

**Comment by nomatterjun** [comment]
![스크린샷 2023-01-25 21 41 50](https://user-images.githubusercontent.com/60438045/214566050-d2125a41-e3ab-48a7-b509-979d7d23d008.png)

들어오긴 했는데..
또 말썽이네 😅
Universal 사이즈로 `svg` 포맷 파일 하나만 올려봐줄 수 있을까??

**Comment by EnnzoKim** [comment]
모든 에셋이 저런 오류가 뜨는거지?
왜 다른 브랜치로가면 말썽인지 모르겠네..

> Universal 사이즈로 svg 포맷 파일 하나만 올려봐줄 수 있을까??

혹시 이 말이 정확히 어떤 뜻인지 알 수 있을까?..

**Comment by nomatterjun** [comment]
https://github.com/Favor-Gift-Reminder/Favor-iOS/discussions/33#discussioncomment-4738478

여기서 말했던 것 처럼 사이즈를 `Single Scale` 하나로 통합해서 올려봐줄 수 있을까?
새로 작업하는 아이콘들은 문제가 없는데 전에 `png`포맷으로 올렸던 애들만 그런건가 싶어서..!

**Comment by EnnzoKim** [comment]
오케이! 푸쉬했어 한번 확인해줘! 

>추가로 `Single Scale`로 설정을 한다면,
피그마에서 어떤 사이즈로 `Export`하는게 좋을까..?

**Comment by nomatterjun** [comment]
<img width="220" alt="스크린샷 2023-01-25 23 56 11" src="https://user-images.githubusercontent.com/60438045/214597317-5d802760-08f1-40ba-8ea1-f3d8c50d81ac.png">

흠..

혹시 내가 올린 에셋들도 이렇게 떠..?

피그마에서 `Export`는 그냥 기본으로 x1 svg옵션 주고 하고 있어..!

**Comment by EnnzoKim** [comment]
아니 나는 형이 올린 에셋들이 오류 없이 잘 떠
왜이러는거지...??? 

> 1x로하면 해상도관련해서 문제는 없을까?? 
Single Scale로 적용하는건 처음이라 잘 모르겠네..

**Comment by nomatterjun** [comment]
정말 모르겠네..

일단 내가 추가해서 푸쉬해봤어 한번 확인 부탁해..!

> 벡터 이미지라 스케일은 사실 상관이 없어! 벡터 이미지는 퀄리티 손상이 안일어나..!

**Comment by EnnzoKim** [comment]
나는 잘 받아와지는 것 같아! 
 
마지막으로 형이 알려준 방법대로
`ic_test` 에셋 내가 한번 추가해볼테니까

풀 해서 잘 받아와지는지 확인해줘!

**Comment by nomatterjun** [comment]
<img width="888" alt="스크린샷 2023-01-26 09 09 58" src="https://user-images.githubusercontent.com/60438045/214722536-562b6132-855d-40db-88ce-40e582c92073.png">

하핫..

뭐가 문제일까..

**Comment by nomatterjun** [comment]
우와.. 진짜 모르겠네..

보니깐 하나로 와야할 속성값들이 저렇게 `Universal`, `Unassigned` 둘로 나뉘어져서 들어와서 그런 것 같아
근데 또 `Contents.json` 파일을 직접 열어서 보면 내용이 똑같네..

**Comment by EnnzoKim** [comment]
다시 한번 풀 해서 확인해줄래?
혹시 이 부분이 문제였나 싶어서!

**Comment by nomatterjun** [comment]
오.. 됐어!! 👏

뭐가 문제였던거야??

**Comment by EnnzoKim** [comment]
역시 ...

Xcode 버그 였던 것 같아
우리가 피그마에서 Export해오면 기본적으로 한글과 특수문자가 포함되어 있는 이름의 파일을 다운받아지는데
이게 문제였던 것 같아..
파일 이름을 영어로 고쳤더니 됐어 ! 

https://stackoverflow.com/questions/50504242/xcode-some-image-assets-appear-unassigned-after-git-clone

다행다행~

**Comment by nomatterjun** [comment]
와우..

한글이 또..
나는 저장할때부터 이름을 바꿔서 저장해서 멀쩡했던 거였나봐..
아무튼 해결방법을 찾아서 다행이다!

👍👍
